appName:
server:
  port: 8888
mysql:
  host: root:123456@tcp(127.0.0.1:3306)/shuvigoss?charset=utf8&parseTime=true
  max: 200
  maxIdle: 10
workPath: /tmp
logFile: /tmp/log/go-seed.log
logLevel: info
